### ISSUE TITLE
Redis now issues warning message regarding Auth information

### ISSUE THREAD

**Issue by russellhill** [jpodwys/cache-service-redis#11]
I think a bump in Redis version has now caused it to emit warning messages when the cache-service-redis connects to it.

These are:

```
node_redis: Deprecated: The AUTH command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
```

and

```
node_redis: Warning: Redis server does not require a password, but a password was supplied.
```

This seems to be caused by this line of code:

https://github.com/jpodwys/cache-service-redis/blob/master/redisCacheModule.js#L351

Which does not check first if there are auth credentials to be passed on to Redis

**Comment by jpodwys** [comment]
Thanks for this. I published release `1.2.3` to NPM. Please close this issue when you confirm.
