### ISSUE TITLE
is there a way to specify redis database number ?

### ISSUE THREAD

**Issue by fadyZohdy** [jpodwys/cache-service-redis#16]

**Comment by jpodwys** [comment]
Great question!

I've exposed the underlying [`node_redis`](https://github.com/NodeRedis/node_redis) instance at `redisCache.db`. I've never tried this before, but the `node_redis` docs say you can select which DB to use as follows: `client.select(3, function() { /* ... */ });`.

With that in mind, you should be able to run `redisCache.db.select(3, function() { /* ... */ });` at which point all subsequent actions will be performed against the redis DB at index 3.

As for `cache-service-redis`'s own public API, there is currently no way to do this on a per-command basis.

**Comment by fadyZohdy** [comment]
this solution works fine for me. thanx.

**Comment by fadyZohdy** [comment]
i can work on passing the database instance in the initialization config and send u a PR. ok ?

**Comment by jpodwys** [comment]
That sounds great, thanks!
