### ISSUE TITLE
expiration by request header cache-control [optional]

### ISSUE THREAD

**Issue by autorTepatiki** [jpodwys/cache-service-redis#19]
Hi John. I would like to be offered the chance to specify that the expiry time, not only as explicit parameter, but to set it upon each request header 'cache-control: max-age=<N>' for example, instead of (or alternativaly to) the configuration module. 

//Require superagent and the cache module I want
const RedisModule = require('cache-service-redis');
const redisDefaults = {cacheWhenEmpty: false, **expiration: 3600**};
let cacheEnv = {redisEnv: 'REDISCLOUD_URL'};
const redisCache = new RedisModule(cacheEnv);
require('superagent-cache')(
            superagent,
            redisCache,
            redisOptions
);

Is it possible?

**Comment by jpodwys** [comment]
If I understand correctly, you would like superagent-cache to respect cache-control headers. If this is correct, there is a fork of superagent-cache-plugin that does what you want. Here is a link:

https://github.com/finanzcheck/superagent-cache-plugin/tree/feature/CORE-440-respect_response_cache_headers

**Comment by autorTepatiki** [comment]
That is. I will get a look at it. Regards.


________________________________
De: Joe Podwys <notifications@github.com>
Enviado: lunes, 7 de octubre de 2019 21:22
Para: jpodwys/cache-service-redis <cache-service-redis@noreply.github.com>
Cc: Martin Dario CERNADAS <martin.cernadas@naranja.com>; Author <author@noreply.github.com>
Asunto: Re: [jpodwys/cache-service-redis] expiration by request header cache-control [optional] (#19)


If I understand correctly, you would like superagent-cache to respect cache-control headers. If this is correct, there is a fork of superagent-cache-plugin that does what you want. Here is a link:

https://github.com/finanzcheck/superagent-cache-plugin/tree/feature/CORE-440-respect_response_cache_headers
