### ISSUE TITLE
Errors when following example

### ISSUE THREAD

**Issue by azhang** [jpodwys/cache-service-redis#2]
http://localhost:6379
cacheService: Error when getting key key1 from cache of type redis: { name: 'GetException',
  message: [TypeError: self.db.get is not a function] }
cacheService: Error when getting key key2 from cache of type redis: { name: 'GetException',
  message: [TypeError: self.db.get is not a function] }
redisCacheModule: .set() failed for cache of type redis { name: 'RedisSetException',
  message: [TypeError: self.db.setex is not a function] }
redisCacheModule: .set() failed for cache of type redis { name: 'RedisSetException',
  message: [TypeError: self.db.setex is not a function] }

**Comment by jpodwys** [comment]
Can you please paste the complete code block you're using that produces these errors?

**Comment by azhang** [comment]
```
import CacheService from 'cache-service';
import CacheServiceRedis from 'cache-service-redis';

var redisCache = new CacheServiceRedis({
  redisMock: true,
  redisUrl: http://localhost:6379});

var cacheModules = [redisCache];

const cache = Promise.promisifyAll(new CacheService({}, cacheModules));


```

The error does not occur when using the default configuration

```
const cache = Promise.promisifyAll(new CacheService()
```

**Comment by jpodwys** [comment]
I believe the problem is that you're passing `redisMock: true`. The [docs](https://github.com/jpodwys/cache-service-redis#using-a-redis-mock) show using an actual [redis mock](https://www.npmjs.com/package/redis-js) as follows:

``` javascript
var redisMock = require('redis-js');
```

**Comment by azhang** [comment]
Here's the output with redisMock commented out:

```
redisCacheModule: Redis client not created: [TypeError: Cannot read property 'split' of null]
cacheService: Error when getting key key1 from cache of type redis: { name: 'GetException',
  message: [TypeError: self.db.get is not a function] }
cacheService: Error when getting key key2 from cache of type redis: { name: 'GetException',
  message: [TypeError: self.db.get is not a function] }
redisCacheModule: .set() failed for cache of type redis { name: 'RedisSetException',
  message: [TypeError: self.db.setex is not a function] }
redisCacheModule: .set() failed for cache of type redis { name: 'RedisSetException',
  message: [TypeError: self.db.setex is not a function] }
```

**Comment by jpodwys** [comment]
Additionally, you should use either a `redisMock` or a `redisUrl`, not both.

As for your latest comment, here's a section from the docs:

> If you have all of your redis params already prepared as a URL in the following format: http://uri:password@hostname:port, then you can simply pass that URL with the object key redisUrl.

Your example `redisUrl` does not match the above format.

**Comment by azhang** [comment]
Ah yes, I just figured that out from sprinkling console.logs in redisCacheModule.js:246, redisURL.auth returns null because there is no authentication string in the url. 

Since I'm running redis locally with no authentication (which might be a common use case), it might be good to check for auth !== null before trying `db.auth`. To work around it for now, I'm using "http://:@localhost:6379"

**Comment by jpodwys** [comment]
That's a great point, thanks! Since you put the time in to find the spot where this was occurring, would you also like to submit a PR and get contributor credit? If not, I can do it soon.
